In [ ]:
# We said that NumPy is pretty much a list on steroids. Let’s see that in action.

# For the tasks below, do them using a regular Python list implementation, and then use NumPy.

# Create a table (i.e. a 2d array) of size M x N filled with random integers between 1 and 100,
# where 1 < N < 40 and 1 < M < 50.

# Print out the third row

# Print out the third column

# Set every element in the last row equal to 7

# Set every element in the last column equal the sum of the first two columns. (note: the result of
# the sum is a list which will the same length as the last column)

In [1]:
import random
import pandas as pd
import numpy as np

In [2]:
def create_mat(M,N):
    if M<50 and N<40:
        return np.random.randint(1,101,(M,N))
print(create_mat(5,6))

[[81 65 51 68 51 96]
 [ 8 47 27 36 99 60]
 [15 62 28 81 38 92]
 [96 37 80 82 97 23]
 [53 21 61 62 17 18]]


In [7]:
a=create_mat(5,6)
print(a)

[[  1 100  41  82  86  36]
 [ 18  63  54  56  93  46]
 [ 43  37   8  98  92  25]
 [ 32  26  82   1  94  12]
 [ 50  18  70  97 100  41]]


In [8]:
print(a[2])

[43 37  8 98 92 25]


In [9]:
print(a[:,3])

[82 56 98  1 97]


In [10]:
a[-1]=7
print(a)

[[  1 100  41  82  86  36]
 [ 18  63  54  56  93  46]
 [ 43  37   8  98  92  25]
 [ 32  26  82   1  94  12]
 [  7   7   7   7   7   7]]


In [12]:
a[:,-1]=a[:,0]+a[:,1]
print(a)

[[  1 100  41  82  86 101]
 [ 18  63  54  56  93  81]
 [ 43  37   8  98  92  80]
 [ 32  26  82   1  94  58]
 [  7   7   7   7   7  14]]
